export const categories = [
  "Fruits et légumes",
  "Conserves",
  "Pâtes et riz",
  "Frais",
  "Surgelés",
  "Crèmerie",
  "Desserts frais",
  "Fromages",
  "Charcuterie",
  "Boucherie",
  "Hygiène",
  "Boissons",
  "Ustensiles",
  "Voiture",
  "Petit déjeuner",
  "Boulangerie",
  "Bio",
  "Foyer / Pharmacie",
  "Bonbons / Snacks",
  "Chips et apéros",
  "Ingrédients de cuisine",
  "Café et thé",
  "Sauces et épices",
  "Condiments et huiles",
  // Ajouts proposés pour compléter
  "Soin de la maison", 
  "Animaux",
  "Bébé",
  "Cave à vin"
].sort();
