export interface Product {
  name: string;
  category: string;
}

export const defaultProductsDatabase: Product[] = [
  // Fruits et légumes
  { name: "Pommes", category: "Fruits et légumes" },
  { name: "Bananes", category: "Fruits et légumes" },
  { name: "Citrons jaunes", category: "Fruits et légumes" },
  { name: "Citrons verts", category: "Fruits et légumes" },
  { name: "Oranges", category: "Fruits et légumes" },
  { name: "Clémentines", category: "Fruits et légumes" },
  { name: "Pamplemousses / Pomelos", category: "Fruits et légumes" },
  { name: "Fraises", category: "Fruits et légumes" },
  { name: "Framboises", category: "Fruits et légumes" },
  { name: "Myrtilles", category: "Fruits et légumes" },
  { name: "Mûres", category: "Fruits et légumes" },
  { name: "Poires", category: "Fruits et légumes" },
  { name: "Pêches", category: "Fruits et légumes" },
  { name: "Nectarines", category: "Fruits et légumes" },
  { name: "Abricots", category: "Fruits et légumes" },
  { name: "Prunes", category: "Fruits et légumes" },
  { name: "Mirabelles", category: "Fruits et légumes" },
  { name: "Cerises", category: "Fruits et légumes" },
  { name: "Raisins blancs", category: "Fruits et légumes" },
  { name: "Raisins noirs", category: "Fruits et légumes" },
  { name: "Melon", category: "Fruits et légumes" },
  { name: "Pastèque", category: "Fruits et légumes" },
  { name: "Figues", category: "Fruits et légumes" },
  { name: "Grenades", category: "Fruits et légumes" },
  { name: "Kiwis", category: "Fruits et légumes" },
  { name: "Mangues", category: "Fruits et légumes" },
  { name: "Ananas", category: "Fruits et légumes" },
  { name: "Fruits de la passion", category: "Fruits et légumes" },
  { name: "Litchis", category: "Fruits et légumes" },
  { name: "Noix", category: "Fruits et légumes" },
  { name: "Noisettes", category: "Fruits et légumes" },
  { name: "Amandes", category: "Fruits et légumes" },
  { name: "Châtaignes / Marrons", category: "Fruits et légumes" },
  { name: "Tomates", category: "Fruits et légumes" },
  { name: "Tomates cerises", category: "Fruits et légumes" },
  { name: "Tomates grappes", category: "Fruits et légumes" },
  { name: "Courgettes", category: "Fruits et légumes" },
  { name: "Aubergines", category: "Fruits et légumes" },
  { name: "Concombres", category: "Fruits et légumes" },
  { name: "Carottes", category: "Fruits et légumes" },
  { name: "Poireaux", category: "Fruits et légumes" },
  { name: "Brocolis", category: "Fruits et légumes" },
  { name: "Chou-fleur", category: "Fruits et légumes" },
  { name: "Chou blanc", category: "Fruits et légumes" },
  { name: "Chou rouge", category: "Fruits et légumes" },
  { name: "Chou vert / frisé", category: "Fruits et légumes" },
  { name: "Choux de Bruxelles", category: "Fruits et légumes" },
  { name: "Salade (Batavia / Laitue)", category: "Fruits et légumes" },
  { name: "Mâche", category: "Fruits et légumes" },
  { name: "Roquette", category: "Fruits et légumes" },
  { name: "Jeunes pousses", category: "Fruits et légumes" },
  { name: "Épinards frais", category: "Fruits et légumes" },
  { name: "Haricots verts", category: "Fruits et légumes" },
  { name: "Haricots plats", category: "Fruits et légumes" },
  { name: "Petits pois frais", category: "Fruits et légumes" },
  { name: "Pois gourmands", category: "Fruits et légumes" },
  { name: "Avocats", category: "Fruits et légumes" },
  { name: "Oignons jaunes", category: "Fruits et légumes" },
  { name: "Oignons rouges", category: "Fruits et légumes" },
  { name: "Oignons blancs", category: "Fruits et légumes" },
  { name: "Cébettes / Oignons nouveaux", category: "Fruits et légumes" },
  { name: "Ail", category: "Fruits et légumes" },
  { name: "Échalotes", category: "Fruits et légumes" },
  { name: "Artichauts", category: "Fruits et légumes" },
  { name: "Patates douces", category: "Fruits et légumes" },
  { name: "Potiron", category: "Fruits et légumes" },
  { name: "Butternut", category: "Fruits et légumes" },
  { name: "Potimarron", category: "Fruits et légumes" },
  { name: "Poivrons (Rouges/Verts/Jaunes)", category: "Fruits et légumes" },
  { name: "Champignons de Paris", category: "Fruits et légumes" },
  { name: "Pleurotes", category: "Fruits et légumes" },
  { name: "Cèpes frais", category: "Fruits et légumes" },
  { name: "Endives", category: "Fruits et légumes" },
  { name: "Céleri branche", category: "Fruits et légumes" },
  { name: "Céleri-rave", category: "Fruits et légumes" },
  { name: "Radis", category: "Fruits et légumes" },
  { name: "Betteraves fraîches", category: "Fruits et légumes" },
  { name: "Fenouil", category: "Fruits et légumes" },
  { name: "Blettes", category: "Fruits et légumes" },
  { name: "Navets", category: "Fruits et légumes" },
  { name: "Panais", category: "Fruits et légumes" },
  { name: "Topinambours", category: "Fruits et légumes" },
  { name: "Menthe fraîche", category: "Fruits et légumes" },
  { name: "Coriandre fraîche", category: "Fruits et légumes" },
  { name: "Persil frais", category: "Fruits et légumes" },
  { name: "Ciboulette fraîche", category: "Fruits et légumes" },
  { name: "Basilic frais", category: "Fruits et légumes" },
  { name: "Pommes de terre (Chair ferme)", category: "Fruits et légumes" },
  { name: "Pommes de terre (Purée/Frites)", category: "Fruits et légumes" },
  { name: "Pommes de terre grenailles", category: "Fruits et légumes" },
  
  // Conserves
  { name: "Haricots verts (boîte)", category: "Conserves" },
  { name: "Haricots beurre (boîte)", category: "Conserves" },
  { name: "Flageolets (boîte)", category: "Conserves" },
  { name: "Haricots blancs (boîte)", category: "Conserves" },
  { name: "Haricots rouges (boîte)", category: "Conserves" },
  { name: "Petits pois (boîte)", category: "Conserves" },
  { name: "Petits pois carottes (boîte)", category: "Conserves" },
  { name: "Lentilles (boîte)", category: "Conserves" },
  { name: "Lentilles préparées (boîte)", category: "Conserves" },
  { name: "Pois chiches (boîte)", category: "Conserves" },
  { name: "Tomates pelées", category: "Conserves" },
  { name: "Tomates concassées", category: "Conserves" },
  { name: "Concentré de tomates", category: "Conserves" },
  { name: "Coulis de tomates", category: "Conserves" },
  { name: "Maïs (boîte)", category: "Conserves" },
  { name: "Coeurs de palmiers (boîte)", category: "Conserves" },
  { name: "Asperges (boîte)", category: "Conserves" },
  { name: "Champignons de Paris (boîte)", category: "Conserves" },
  { name: "Macédoine de légumes", category: "Conserves" },
  { name: "Ratatouille (boîte)", category: "Conserves" },
  { name: "Cassoulet (boîte)", category: "Conserves" },
  { name: "Choucroute (boîte)", category: "Conserves" },
  { name: "Raviolis (boîte)", category: "Conserves" },
  { name: "Sardines à l'huile", category: "Conserves" },
  { name: "Sardines à la tomate", category: "Conserves" },
  { name: "Maquereaux", category: "Conserves" },
  { name: "Thon au naturel", category: "Conserves" },
  { name: "Thon à l'huile", category: "Conserves" },
  { name: "Thon à la tomate", category: "Conserves" },
  { name: "Anchois", category: "Conserves" },
  { name: "Pâté Hénaff", category: "Conserves" },
  { name: "Corned beef", category: "Conserves" },
  { name: "Rillettes (boîte)", category: "Conserves" },
  { name: "Ananas en tranches (boîte)", category: "Conserves" },
  { name: "Pêches au sirop", category: "Conserves" },
  { name: "Poires au sirop", category: "Conserves" },
  { name: "Cocktail de fruits au sirop", category: "Conserves" },

  // Pâtes et riz
  { name: "Pâtes", category: "Pâtes et riz" },
  { name: "Coquillettes", category: "Pâtes et riz" },
  { name: "Spaghettis", category: "Pâtes et riz" },
  { name: "Pennes", category: "Pâtes et riz" },
  { name: "Macaronis", category: "Pâtes et riz" },
  { name: "Farfalles", category: "Pâtes et riz" },
  { name: "Fusilli", category: "Pâtes et riz" },
  { name: "Tagliatelles", category: "Pâtes et riz" },
  { name: "Linguine", category: "Pâtes et riz" },
  { name: "Lasagnes (sèches)", category: "Pâtes et riz" },
  { name: "Cannelloni", category: "Pâtes et riz" },
  { name: "Vermicelles", category: "Pâtes et riz" },
  { name: "Pâtes coquillages", category: "Pâtes et riz" },
  { name: "Pâtes complètes / blé complet", category: "Pâtes et riz" },
  { name: "Pâtes sans gluten", category: "Pâtes et riz" },
  { name: "Nouilles chinoises", category: "Pâtes et riz" },
  { name: "Nouilles de riz", category: "Pâtes et riz" },
  { name: "Nouilles Udon", category: "Pâtes et riz" },
  { name: "Riz blanc", category: "Pâtes et riz" },
  { name: "Riz basmati", category: "Pâtes et riz" },
  { name: "Riz thaï", category: "Pâtes et riz" },
  { name: "Riz rond (Dessert/Risotto)", category: "Pâtes et riz" },
  { name: "Riz complet", category: "Pâtes et riz" },
  { name: "Riz à sushis", category: "Pâtes et riz" },
  { name: "Semoule (Couscous fin)", category: "Pâtes et riz" },
  { name: "Semoule (Couscous moyen)", category: "Pâtes et riz" },
  { name: "Quinoa", category: "Pâtes et riz" },
  { name: "Boulgour", category: "Pâtes et riz" },
  { name: "Ebly / Blé", category: "Pâtes et riz" },
  { name: "Polenta", category: "Pâtes et riz" },
  { name: "Lentilles corail", category: "Pâtes et riz" },
  { name: "Lentilles vertes (Céréale)", category: "Pâtes et riz" },
  { name: "Pois cassés secs", category: "Pâtes et riz" },

  // Frais & Plats préparés & Poissons
  { name: "Pâtes fraîches", category: "Frais" },
  { name: "Gnocchis", category: "Frais" },
  { name: "Raviolis frais", category: "Frais" },
  { name: "Tortellini frais", category: "Frais" },
  { name: "Pâte à tarte (brisée)", category: "Frais" },
  { name: "Pâte feuilletée", category: "Frais" },
  { name: "Pâte à pizza", category: "Frais" },
  { name: "Pâte sablée", category: "Frais" },
  { name: "Feuilles de brick", category: "Frais" },
  { name: "Pizza (Frais)", category: "Frais" },
  { name: "Quiche (Frais)", category: "Frais" },
  { name: "Croque-monsieur (Frais)", category: "Frais" },
  { name: "Cordons bleus", category: "Frais" },
  { name: "Friands (viande/fromage)", category: "Frais" },
  { name: "Nuggets de poulet (Frais)", category: "Frais" },
  { name: "Nems (Frais)", category: "Frais" },
  { name: "Samoussas (Frais)", category: "Frais" },
  { name: "Rouleaux de printemps", category: "Frais" },
  { name: "Falafels (Frais)", category: "Frais" },
  { name: "Gaspacho", category: "Frais" },
  { name: "Houmous", category: "Frais" },
  { name: "Tarama", category: "Frais" },
  { name: "Tzatziki", category: "Frais" },
  { name: "Guacamole", category: "Frais" },
  { name: "Blinis", category: "Frais" },
  { name: "Tapenade", category: "Frais" },
  { name: "Salade piémontaise (Frais)", category: "Frais" },
  { name: "Carottes râpées (Frais)", category: "Frais" },
  { name: "Céleri rémoulade (Frais)", category: "Frais" },
  { name: "Taboulé (Frais)", category: "Frais" },
  { name: "Surimi", category: "Frais" },
  { name: "Saumon fumé", category: "Frais" },
  { name: "Truite fumée", category: "Frais" },
  { name: "Pavés de saumon (Frais)", category: "Frais" },
  { name: "Dos de cabillaud (Frais)", category: "Frais" },
  { name: "Filets de lieu (Frais)", category: "Frais" },
  { name: "Crevettes roses", category: "Frais" },
  { name: "Crevettes grises", category: "Frais" },
  { name: "Gambas (Fraîches)", category: "Frais" },
  { name: "St-Jacques (Fraîches)", category: "Frais" },
  { name: "Moules", category: "Frais" },
  { name: "Huîtres", category: "Frais" },

  // Surgelés
  { name: "Légumes surgelés mixtes", category: "Surgelés" },
  { name: "Haricots verts surgelés", category: "Surgelés" },
  { name: "Petits pois surgelés", category: "Surgelés" },
  { name: "Brocolis surgelés", category: "Surgelés" },
  { name: "Chou-fleur surgelé", category: "Surgelés" },
  { name: "Épinards hachés surgelés", category: "Surgelés" },
  { name: "Épinards en branches surgelés", category: "Surgelés" },
  { name: "Poêlée paysanne", category: "Surgelés" },
  { name: "Wok de légumes surgelés", category: "Surgelés" },
  { name: "Oignons émincés surgelés", category: "Surgelés" },
  { name: "Frites surgelées", category: "Surgelés" },
  { name: "Potatoes", category: "Surgelés" },
  { name: "Pommes noisettes", category: "Surgelés" },
  { name: "Pommes dauphines", category: "Surgelés" },
  { name: "Purée surgelée", category: "Surgelés" },
  { name: "Pizza surgelée", category: "Surgelés" },
  { name: "Tarte flambée surgelée", category: "Surgelés" },
  { name: "Lasagnes surgelées", category: "Surgelés" },
  { name: "Hachis Parmentier surgelé", category: "Surgelés" },
  { name: "Steaks hachés surgelés (Pur bœuf)", category: "Surgelés" },
  { name: "Burgers végétariens surgelés", category: "Surgelés" },
  { name: "Nuggets surgelés", category: "Surgelés" },
  { name: "Poisson pané", category: "Surgelés" },
  { name: "Filets de poisson surgelés", category: "Surgelés" },
  { name: "Saumon surgelé", category: "Surgelés" },
  { name: "Crevettes surgelées", category: "Surgelés" },
  { name: "Glace / Crème glacée Vanille", category: "Surgelés" },
  { name: "Glace / Crème glacée Chocolat", category: "Surgelés" },
  { name: "Sorbet Citron", category: "Surgelés" },
  { name: "Sorbet Framboise", category: "Surgelés" },
  { name: "Cônes glacés (Extrême/Cornetto)", category: "Surgelés" },
  { name: "Bâtonnets glacés (Magnum/Esquimaux)", category: "Surgelés" },
  { name: "Glaçons", category: "Surgelés" },

  // Crèmerie
  { name: "Beurre doux", category: "Crèmerie" },
  { name: "Beurre demi-sel", category: "Crèmerie" },
  { name: "Margarine", category: "Crèmerie" },
  { name: "Crème fraîche épaisse", category: "Crèmerie" },
  { name: "Crème fraîche liquide entière", category: "Crèmerie" },
  { name: "Crème liquide allégée", category: "Crèmerie" },
  { name: "Crème fleurette", category: "Crèmerie" },
  { name: "Lait entier", category: "Crèmerie" },
  { name: "Lait demi-écrémé", category: "Crèmerie" },
  { name: "Lait écrémé", category: "Crèmerie" },
  { name: "Lait sans lactose", category: "Crèmerie" },
  { name: "Œufs", category: "Crèmerie" },
  { name: "Yaourts nature", category: "Crèmerie" },
  { name: "Yaourts sucrés", category: "Crèmerie" },
  { name: "Yaourts aux fruits", category: "Crèmerie" },
  { name: "Yaourts à boire (Yop...)", category: "Crèmerie" },
  { name: "Yaourts à la grecque", category: "Crèmerie" },
  { name: "Yaourts au lait de brebis / chèvre", category: "Crèmerie" },
  { name: "Petit-suisse", category: "Crèmerie" },
  { name: "Fromage blanc", category: "Crèmerie" },
  { name: "Fromage blanc 0%", category: "Crèmerie" },
  { name: "Faisselle", category: "Crèmerie" },
  { name: "Skyr", category: "Crèmerie" },
  { name: "Mascarpone", category: "Crèmerie" },

  // Desserts frais
  { name: "Crème dessert Chocolat", category: "Desserts frais" },
  { name: "Crème dessert Vanille", category: "Desserts frais" },
  { name: "Mousse au chocolat", category: "Desserts frais" },
  { name: "Île flottante", category: "Desserts frais" },
  { name: "Riz au lait", category: "Desserts frais" },
  { name: "Liégeois", category: "Desserts frais" },
  { name: "Flans", category: "Desserts frais" },
  { name: "Tiramisu (frais)", category: "Desserts frais" },
  { name: "Profiteroles (frais)", category: "Desserts frais" },
  { name: "Compote (frais)", category: "Desserts frais" },

  // Fromages
  { name: "Emmental râpé", category: "Fromages" },
  { name: "Gruyère râpé", category: "Fromages" },
  { name: "Emmental en bloc", category: "Fromages" },
  { name: "Parmesan râpé", category: "Fromages" },
  { name: "Parmesan en bloc (Parmigiano)", category: "Fromages" },
  { name: "Grana Padano", category: "Fromages" },
  { name: "Mozzarella (boule)", category: "Fromages" },
  { name: "Mozzarella di Bufala", category: "Fromages" },
  { name: "Mozzarella râpée/spécial cuisine", category: "Fromages" },
  { name: "Camembert", category: "Fromages" },
  { name: "Brie", category: "Fromages" },
  { name: "Coulommiers", category: "Fromages" },
  { name: "Roquefort", category: "Fromages" },
  { name: "Bleu d'Auvergne", category: "Fromages" },
  { name: "Gorgonzola", category: "Fromages" },
  { name: "Kiri", category: "Fromages" },
  { name: "Babybel", category: "Fromages" },
  { name: "Vache qui rit", category: "Fromages" },
  { name: "Fromage à raclette", category: "Fromages" },
  { name: "Reblochon (Tartiflette)", category: "Fromages" },
  { name: "Bûche de Chèvre", category: "Fromages" },
  { name: "Crottin de chèvre", category: "Fromages" },
  { name: "Rocamadour / Cabécou", category: "Fromages" },
  { name: "Feta", category: "Fromages" },
  { name: "Burrata", category: "Fromages" },
  { name: "Cheddar (tranches)", category: "Fromages" },
  { name: "Cheddar (bloc)", category: "Fromages" },
  { name: "Comté", category: "Fromages" },
  { name: "Cantal", category: "Fromages" },
  { name: "Beaufort", category: "Fromages" },
  { name: "Saint-Nectaire", category: "Fromages" },
  { name: "Morbier", category: "Fromages" },
  { name: "Tomme de Savoie", category: "Fromages" },
  { name: "Mimolette", category: "Fromages" },
  { name: "Gouda", category: "Fromages" },
  { name: "Edam", category: "Fromages" },
  { name: "Fromage à tartiner (Ail et fines herbes)", category: "Fromages" },
  { name: "Croque-monsieur (Tranches fondues)", category: "Fromages" },

  // Charcuterie
  { name: "Jambon blanc", category: "Charcuterie" },
  { name: "Jambon cru (Bayonne, Parme, Serrano)", category: "Charcuterie" },
  { name: "Lardons natures", category: "Charcuterie" },
  { name: "Lardons fumés", category: "Charcuterie" },
  { name: "Bacon", category: "Charcuterie" },
  { name: "Poitrine fumée", category: "Charcuterie" },
  { name: "Saucisson sec", category: "Charcuterie" },
  { name: "Saucisson à l'ail", category: "Charcuterie" },
  { name: "Chorizo", category: "Charcuterie" },
  { name: "Rosette", category: "Charcuterie" },
  { name: "Coppa", category: "Charcuterie" },
  { name: "Pancetta", category: "Charcuterie" },
  { name: "Viande des Grisons", category: "Charcuterie" },
  { name: "Saucisses de Strasbourg (Knacki)", category: "Charcuterie" },
  { name: "Saucisse de Morteau", category: "Charcuterie" },
  { name: "Saucisse de Montbéliard", category: "Charcuterie" },
  { name: "Boudin noir", category: "Charcuterie" },
  { name: "Boudin blanc", category: "Charcuterie" },
  { name: "Rillettes de porc", category: "Charcuterie" },
  { name: "Rillettes de canard / oie", category: "Charcuterie" },
  { name: "Pâté de campagne", category: "Charcuterie" },
  { name: "Pâté de foie / Mousse de canard", category: "Charcuterie" },
  { name: "Pâté en croûte", category: "Charcuterie" },
  { name: "Saucisson brioché", category: "Charcuterie" },

  // Boucherie
  { name: "Steak haché (Frais)", category: "Boucherie" },
  { name: "Viande hachée pur bœuf", category: "Boucherie" },
  { name: "Steak de bœuf", category: "Boucherie" },
  { name: "Faux-filet", category: "Boucherie" },
  { name: "Entrecôte", category: "Boucherie" },
  { name: "Côte de bœuf", category: "Boucherie" },
  { name: "Rumsteak", category: "Boucherie" },
  { name: "Bavette", category: "Boucherie" },
  { name: "Viande à fondue / bourguignon", category: "Boucherie" },
  { name: "Filet de poulet", category: "Boucherie" },
  { name: "Blancs de poulet", category: "Boucherie" },
  { name: "Cuisse de poulet", category: "Boucherie" },
  { name: "Poulet entier", category: "Boucherie" },
  { name: "Pilon de poulet", category: "Boucherie" },
  { name: "Escalopes de dinde", category: "Boucherie" },
  { name: "Rôti de dinde", category: "Boucherie" },
  { name: "Rôti de bœuf", category: "Boucherie" },
  { name: "Rôti de porc", category: "Boucherie" },
  { name: "Côtes de porc", category: "Boucherie" },
  { name: "Filet mignon de porc", category: "Boucherie" },
  { name: "Sauté de porc", category: "Boucherie" },
  { name: "Escalope de veau", category: "Boucherie" },
  { name: "Blanquette de veau", category: "Boucherie" },
  { name: "Magret de canard", category: "Boucherie" },
  { name: "Cuisse de canard confite", category: "Boucherie" },
  { name: "Saucisses de Toulouse", category: "Boucherie" },
  { name: "Chipolatas", category: "Boucherie" },
  { name: "Merguez", category: "Boucherie" },
  { name: "Chair à saucisse / Farce", category: "Boucherie" },

  // Hygiène
  { name: "Dentifrice", category: "Hygiène" },
  { name: "Brosse à dents", category: "Hygiène" },
  { name: "Bain de bouche", category: "Hygiène" },
  { name: "Fil dentaire", category: "Hygiène" },
  { name: "Gel douche", category: "Hygiène" },
  { name: "Savon pour les mains (liquide)", category: "Hygiène" },
  { name: "Savon solide (Marseille/Alep)", category: "Hygiène" },
  { name: "Shampooing", category: "Hygiène" },
  { name: "Après-shampooing", category: "Hygiène" },
  { name: "Gel fixant / Laque", category: "Hygiène" },
  { name: "Déodorant (spray/bille)", category: "Hygiène" },
  { name: "Mousse à raser / Gel à raser", category: "Hygiène" },
  { name: "Lotion après-rasage", category: "Hygiène" },
  { name: "Lames de rasoir", category: "Hygiène" },
  { name: "Papier toilette", category: "Hygiène" },
  { name: "Mouchoirs (paquets/boîtes)", category: "Hygiène" },
  { name: "Coton-tige", category: "Hygiène" },
  { name: "Disques à démaquiller (Coton)", category: "Hygiène" },
  { name: "Eau micellaire / Démaquillant", category: "Hygiène" },
  { name: "Crème hydratante corps", category: "Hygiène" },
  { name: "Crème hydratante visage", category: "Hygiène" },
  { name: "Protections hygiéniques (Serviettes)", category: "Hygiène" },
  { name: "Protections hygiéniques (Tampons)", category: "Hygiène" },
  { name: "Protège-slips", category: "Hygiène" },
  { name: "Gel intime", category: "Hygiène" },
  { name: "Crème solaire / Après-soleil", category: "Hygiène" },

  // Soin de la maison
  { name: "Lessive liquide", category: "Soin de la maison" },
  { name: "Lessive en poudre / capsules", category: "Soin de la maison" },
  { name: "Adoucissant / Soupline", category: "Soin de la maison" },
  { name: "Détachant linge", category: "Soin de la maison" },
  { name: "Liquide vaisselle", category: "Soin de la maison" },
  { name: "Pastilles / Gel lave-vaisselle", category: "Soin de la maison" },
  { name: "Sel régénérant lave-vaisselle", category: "Soin de la maison" },
  { name: "Liquide de rinçage lave-vaisselle", category: "Soin de la maison" },
  { name: "Éponges", category: "Soin de la maison" },
  { name: "Sacs poubelle 30L/50L", category: "Soin de la maison" },
  { name: "Essuie-tout / Sopalin", category: "Soin de la maison" },
  { name: "Nettoyant multi-usages", category: "Soin de la maison" },
  { name: "Nettoyant vitres", category: "Soin de la maison" },
  { name: "Nettoyant sols", category: "Soin de la maison" },
  { name: "Nettoyant salle de bain / Anticalcaire", category: "Soin de la maison" },
  { name: "Désodorisant WC / Canard", category: "Soin de la maison" },
  { name: "Eau de Javel", category: "Soin de la maison" },
  { name: "Chiffons microfibres", category: "Soin de la maison" },
  { name: "Papier cuisson (Sulfurisé)", category: "Soin de la maison" },
  { name: "Papier aluminium", category: "Soin de la maison" },
  { name: "Film étirable", category: "Soin de la maison" },
  { name: "Sacs congélation", category: "Soin de la maison" },
  { name: "Piles (AA / AAA)", category: "Soin de la maison" },
  { name: "Ampoules", category: "Soin de la maison" },
  { name: "Bougies / Allumettes", category: "Soin de la maison" },

  // Animaux
  { name: "Croquettes pour chien", category: "Animaux" },
  { name: "Pâtée / Boîtes pour chien", category: "Animaux" },
  { name: "Friandises pour chien", category: "Animaux" },
  { name: "Croquettes pour chat", category: "Animaux" },
  { name: "Pâtée / Sachets pour chat", category: "Animaux" },
  { name: "Friandises pour chat", category: "Animaux" },
  { name: "Litière pour chat", category: "Animaux" },

  // Bébé
  { name: "Couches", category: "Bébé" },
  { name: "Lingettes bébé", category: "Bébé" },
  { name: "Lait infantile 1er/2ème âge", category: "Bébé" },
  { name: "Lait de croissance", category: "Bébé" },
  { name: "Petits pots salés", category: "Bébé" },
  { name: "Compotes bébé", category: "Bébé" },
  { name: "Plats préparés bébé", category: "Bébé" },
  { name: "Céréales bébé", category: "Bébé" },
  { name: "Gel lavant bébé", category: "Bébé" },
  { name: "Sérum physiologique", category: "Bébé" },
  { name: "Coton bébé", category: "Bébé" },

  // Boissons
  { name: "Eau plate en bouteille", category: "Boissons" },
  { name: "Eau pétillante (Gazeuse)", category: "Boissons" },
  { name: "Pur jus d'orange", category: "Boissons" },
  { name: "Jus de pomme", category: "Boissons" },
  { name: "Jus multifruits", category: "Boissons" },
  { name: "Jus de raisin", category: "Boissons" },
  { name: "Jus de pamplemousse", category: "Boissons" },
  { name: "Limonade", category: "Boissons" },
  { name: "Sirop de menthe", category: "Boissons" },
  { name: "Sirop de grenadine", category: "Boissons" },
  { name: "Sirop de citron/fraise", category: "Boissons" },
  { name: "Cola (Coca-Cola / Pepsi)", category: "Boissons" },
  { name: "Thé glacé (Ice Tea)", category: "Boissons" },
  { name: "Soda aux fruits (Oasis, Fanta...)", category: "Boissons" },
  { name: "Tonic", category: "Boissons" },
  { name: "Lait d'amande", category: "Boissons" },
  { name: "Lait de soja", category: "Boissons" },
  { name: "Lait d'avoine", category: "Boissons" },
  { name: "Boisson énergétique", category: "Boissons" },

  // Café et thé
  { name: "Café moulu", category: "Café et thé" },
  { name: "Café en grains", category: "Café et thé" },
  { name: "Café soluble (Instantané)", category: "Café et thé" },
  { name: "Dosettes / Capsules de café", category: "Café et thé" },
  { name: "Thé vert (sachets)", category: "Café et thé" },
  { name: "Thé noir (sachets)", category: "Café et thé" },
  { name: "Infusion / Tisane (Verveine, Nuit...)", category: "Café et thé" },
  { name: "Chicorée", category: "Café et thé" },

  // Petit déjeuner
  { name: "Céréales (chocolat, miel...)", category: "Petit déjeuner" },
  { name: "Muesli", category: "Petit déjeuner" },
  { name: "Flocons d'avoine", category: "Petit déjeuner" },
  { name: "Pâte à tartiner (Nutella...)", category: "Petit déjeuner" },
  { name: "Confiture de fraise", category: "Petit déjeuner" },
  { name: "Confiture d'abricot", category: "Petit déjeuner" },
  { name: "Confiture de framboise", category: "Petit déjeuner" },
  { name: "Miel", category: "Petit déjeuner" },
  { name: "Beurre de cacahuète", category: "Petit déjeuner" },
  { name: "Chocolat en poudre (Nesquik...)", category: "Petit déjeuner" },
  { name: "Biscuits petit déjeuner (Belvita...)", category: "Petit déjeuner" },

  // Boulangerie
  { name: "Pain de mie", category: "Boulangerie" },
  { name: "Pain de mie complet / céréales", category: "Boulangerie" },
  { name: "Pain hamburger / Buns", category: "Boulangerie" },
  { name: "Baguette / Pain", category: "Boulangerie" },
  { name: "Pain aux céréales", category: "Boulangerie" },
  { name: "Brioche tressée / tranchée", category: "Boulangerie" },
  { name: "Pain au lait", category: "Boulangerie" },
  { name: "Croissants", category: "Boulangerie" },
  { name: "Pains au chocolat", category: "Boulangerie" },
  { name: "Chouquettes", category: "Boulangerie" },
  { name: "Biscottes", category: "Boulangerie" },
  { name: "Pain grillé / Suédois", category: "Boulangerie" },
  { name: "Crêpes (sachet)", category: "Boulangerie" },
  { name: "Gaufres", category: "Boulangerie" },
  { name: "Wraps / Tortillas", category: "Boulangerie" },
  { name: "Pains pita", category: "Boulangerie" },

  // Bonbons / Snacks
  { name: "Chocolat noir (tablette)", category: "Bonbons / Snacks" },
  { name: "Chocolat au lait (tablette)", category: "Bonbons / Snacks" },
  { name: "Chocolat praliné / noisette", category: "Bonbons / Snacks" },
  { name: "Chocolat blanc", category: "Bonbons / Snacks" },
  { name: "Biscuits sablés / Petits beurres", category: "Bonbons / Snacks" },
  { name: "Cookies", category: "Bonbons / Snacks" },
  { name: "Biscuits fourrés (Prince, BN...)", category: "Bonbons / Snacks" },
  { name: "Barres chocolatées (Mars, Snickers...)", category: "Bonbons / Snacks" },
  { name: "Madeleines", category: "Bonbons / Snacks" },
  { name: "Quatre-quarts / Gâteaux moelleux", category: "Bonbons / Snacks" },
  { name: "Pain d'épices", category: "Bonbons / Snacks" },
  { name: "Boudoirs", category: "Bonbons / Snacks" },
  { name: "Bonbons gélifiés (Haribo...)", category: "Bonbons / Snacks" },
  { name: "Caramels", category: "Bonbons / Snacks" },
  { name: "Chewing-gum", category: "Bonbons / Snacks" },

  // Chips et apéros
  { name: "Chips natures", category: "Chips et apéros" },
  { name: "Chips aromatisées (Barbecue/Poulet...)", category: "Chips et apéros" },
  { name: "Chips à l'ancienne", category: "Chips et apéros" },
  { name: "Cacahuètes grillées / salées", category: "Chips et apéros" },
  { name: "Noix de cajou", category: "Chips et apéros" },
  { name: "Pistaches", category: "Chips et apéros" },
  { name: "Amandes grillées (apéro)", category: "Chips et apéros" },
  { name: "Mélange apéritif", category: "Chips et apéros" },
  { name: "Biscuits apéritifs (Tuiles, Belin...)", category: "Chips et apéros" },
  { name: "Bretzels / Sticks salés", category: "Chips et apéros" },
  { name: "Tortillas chips / Nachos", category: "Chips et apéros" },
  { name: "Olives vertes", category: "Chips et apéros" },
  { name: "Olives noires", category: "Chips et apéros" },

  // Ingrédients de cuisine
  { name: "Farine de blé", category: "Ingrédients de cuisine" },
  { name: "Farine complète", category: "Ingrédients de cuisine" },
  { name: "Sucre en poudre", category: "Ingrédients de cuisine" },
  { name: "Sucre en morceaux", category: "Ingrédients de cuisine" },
  { name: "Cassonade / Sucre roux", category: "Ingrédients de cuisine" },
  { name: "Sucre glace", category: "Ingrédients de cuisine" },
  { name: "Levure chimique", category: "Ingrédients de cuisine" },
  { name: "Levure de boulanger", category: "Ingrédients de cuisine" },
  { name: "Sucre vanillé", category: "Ingrédients de cuisine" },
  { name: "Cacao en poudre non sucré", category: "Ingrédients de cuisine" },
  { name: "Extrait de vanille / Gousses", category: "Ingrédients de cuisine" },
  { name: "Pépites de chocolat", category: "Ingrédients de cuisine" },
  { name: "Amandes en poudre", category: "Ingrédients de cuisine" },
  { name: "Amandes effilées", category: "Ingrédients de cuisine" },
  { name: "Noix de coco râpée", category: "Ingrédients de cuisine" },
  { name: "Chapelure", category: "Ingrédients de cuisine" },
  { name: "Maïzena / Fécule de maïs", category: "Ingrédients de cuisine" },
  { name: "Bicarbonate de soude", category: "Ingrédients de cuisine" },

  // Sauces et épices
  { name: "Sel fin", category: "Sauces et épices" },
  { name: "Gros sel", category: "Sauces et épices" },
  { name: "Fleur de sel", category: "Sauces et épices" },
  { name: "Poivre noir (moulu / grains)", category: "Sauces et épices" },
  { name: "Herbes de Provence", category: "Sauces et épices" },
  { name: "Basilic séché", category: "Sauces et épices" },
  { name: "Origan séché", category: "Sauces et épices" },
  { name: "Ciboulette séchée", category: "Sauces et épices" },
  { name: "Persil séché", category: "Sauces et épices" },
  { name: "Paprika", category: "Sauces et épices" },
  { name: "Curry", category: "Sauces et épices" },
  { name: "Cumin", category: "Sauces et épices" },
  { name: "Cannelle", category: "Sauces et épices" },
  { name: "Noix de muscade", category: "Sauces et épices" },
  { name: "Gingembre en poudre", category: "Sauces et épices" },
  { name: "Piment (Doux / Fort / Espelette)", category: "Sauces et épices" },
  { name: "Curcuma", category: "Sauces et épices" },
  { name: "Sauce Pesto", category: "Sauces et épices" },
  { name: "Sauce Bolognaise", category: "Sauces et épices" },
  { name: "Sauce Tomate (Pot)", category: "Sauces et épices" },
  { name: "Lait de coco (cuisine)", category: "Sauces et épices" },
  { name: "Crème de coco", category: "Sauces et épices" },
  { name: "Ketchup", category: "Sauces et épices" },
  { name: "Mayonnaise", category: "Sauces et épices" },
  { name: "Moutarde forte", category: "Sauces et épices" },
  { name: "Moutarde à l'ancienne", category: "Sauces et épices" },
  { name: "Sauce béarnaise / burger", category: "Sauces et épices" },

  // Condiments et huiles
  { name: "Huile d'olive", category: "Condiments et huiles" },
  { name: "Huile de tournesol", category: "Condiments et huiles" },
  { name: "Huile de colza", category: "Condiments et huiles" },
  { name: "Huile de noix / sésame", category: "Condiments et huiles" },
  { name: "Vinaigre balsamique", category: "Condiments et huiles" },
  { name: "Vinaigre blanc (cuisine)", category: "Condiments et huiles" },
  { name: "Vinaigre de cidre", category: "Condiments et huiles" },
  { name: "Cornichons", category: "Condiments et huiles" },
  { name: "Câpres", category: "Condiments et huiles" },
  { name: "Bouillons cubes (Volaille/Bœuf/Légumes)", category: "Condiments et huiles" },
  { name: "Sauce soja (salée)", category: "Condiments et huiles" },
  { name: "Sauce soja (sucrée)", category: "Condiments et huiles" },

  // Cave à vin / Alcools
  { name: "Bière blonde (Pack)", category: "Cave à vin" },
  { name: "Bière de spécialité / IPA", category: "Cave à vin" },
  { name: "Vin rouge", category: "Cave à vin" },
  { name: "Vin blanc sec / moelleux", category: "Cave à vin" },
  { name: "Vin rosé", category: "Cave à vin" },
  { name: "Champagne", category: "Cave à vin" },
  { name: "Crémant / Mousseux", category: "Cave à vin" },
  { name: "Rhum", category: "Cave à vin" },
  { name: "Vodka", category: "Cave à vin" },
  { name: "Whisky", category: "Cave à vin" },
  { name: "Gin", category: "Cave à vin" },
  { name: "Pastis / Ricard", category: "Cave à vin" },
  { name: "Cidre brut / doux", category: "Cave à vin" },
  { name: "Liqueur / Digestif", category: "Cave à vin" }
];

// Calcul de la distance de Levenshtein (mesure la différence entre deux mots)
function levenshteinDistance(s1: string, s2: string): number {
  if (s1.length === 0) return s2.length;
  if (s2.length === 0) return s1.length;
  const matrix = Array(s1.length + 1).fill(null).map(() => Array(s2.length + 1).fill(null));
  for (let i = 0; i <= s1.length; i += 1) matrix[i][0] = i;
  for (let j = 0; j <= s2.length; j += 1) matrix[0][j] = j;
  for (let i = 1; i <= s1.length; i += 1) {
    for (let j = 1; j <= s2.length; j += 1) {
      const cost = s1[i - 1] === s2[j - 1] ? 0 : 1;
      matrix[i][j] = Math.min(
        matrix[i - 1][j] + 1,
        matrix[i][j - 1] + 1,
        matrix[i - 1][j - 1] + cost
      );
    }
  }
  return matrix[s1.length][s2.length];
}

export function searchLocalProducts(query: string): Product[] {
  if (!query || query.length < 2) return [];
  
  // Suppression des accents et mise en minuscules pour une recherche plus large
  const normalize = (str: string) => str.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().trim();
  const normalizedQuery = normalize(query);
  
  const scoredProducts = defaultProductsDatabase.map(p => {
    const normalizedName = normalize(p.name);
    
    // Cas 1 : Le nom contient exactement la recherche (ou inversement) -> meilleur score
    if (normalizedName.includes(normalizedQuery)) return { product: p, score: 0 };
    if (normalizedQuery.includes(normalizedName)) return { product: p, score: 1 };
    
    // Cas 2 : Recherche floue (pour les fautes de frappe comme canelle au lieu de cannelle)
    const words = normalizedName.split(/[\s,()/'-]+/);
    const queryWords = normalizedQuery.split(/[\s,()/'-]+/);
    
    let bestScore = Infinity;
    
    for (const qWord of queryWords) {
      if (qWord.length < 3) continue; // On ignore les tout petits mots
      for (const w of words) {
        if (w.length < 3) continue;
        
        const dist = levenshteinDistance(qWord, w);
        // Si la différence est de 1 ou 2 lettres maximum (faute de frappe acceptable)
        if (dist <= 2) {
          // On ajoute un malus de "2" pour prioriser les correspondances exactes
          bestScore = Math.min(bestScore, dist + 2);
        }
      }
    }
    
    return { product: p, score: bestScore };
  });
  
  // On garde ceux qui ont un score valide (match exact ou petite faute de frappe)
  const results = scoredProducts.filter(item => item.score < Infinity);
  
  // On trie par score (les correspondances exactes en premier)
  results.sort((a, b) => {
    if (a.score !== b.score) return a.score - b.score;
    // En cas d'égalité (même score), on départage par rapport au début du mot ou à la longueur
    const aLower = normalize(a.product.name);
    const bLower = normalize(b.product.name);
    const aStarts = aLower.startsWith(normalizedQuery);
    const bStarts = bLower.startsWith(normalizedQuery);
    
    if (aStarts && !bStarts) return -1;
    if (!aStarts && bStarts) return 1;
    return a.product.name.length - b.product.name.length;
  });

  return results.slice(0, 10).map(r => r.product);
}

